name: basic-web-app-2

on:

push:

branches:

- main

jobs:

basic-web-app-2:

    runs-on: ubuntu-latest

    name: Basic Web App

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run link

    - run: npm run test
